
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libportaudio2 portaudio19-dev cmake lib64ncurses5-dev lib64ncurses5 flex bison
before_script:
  - ./install-protobuf.sh
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --all
