language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libportaudio2 portaudio19-dev cmake lib64ncurses5-dev
  - sudo apt-get install -y lib64ncurses5 flex bison libsndfile1-dev libsndfile1
env:
  - CSOUND_LIB_DIR=/usr/local/lib

before_script:
  - ./install_csound.sh

script:
  - cargo build --verbose --all
