dist: xenial
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libportaudio2 portaudio19-dev cmake lib64ncurses5-dev
  - sudo apt-get install -y lib64ncurses5 flex bison libsndfile1-dev libsndfile1
addons:
  apt:
    update: true
env:
  - CSOUND_LIB_DIR=/usr/local/lib


install:
  - command -v mdbook >/dev/null 2>&1 || cargo install mdbook
  - command -v mdbook-linkcheck >/dev/null 2>&1 || cargo install mdbook-linkcheck

before_script:
  - ./install_csound.sh

script:
  - cargo build --verbose --all
  - cargo doc --verbose
