dist: xenial
language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      install: true

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
      install: true

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      install: true

  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libportaudio2 portaudio19-dev cmake lib64ncurses5-dev
  - sudo apt-get install -y lib64ncurses5 flex bison libsndfile1-dev libsndfile1
before_install:
  - sudo apt-get install -y build-essential
addons:
  apt:
    update: true
env:
  - CSOUND_LIB_DIR=/usr/local/lib

before_script:
  - ./install_csound.sh

script:
  - cargo build --verbose --all
