[package]
name = "csound"
version = "0.1.0"
authors = ["Natanael Mojica <neithanmo@gmail.com"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["csound", "audio", "dsp", "music", "multimedia"]
repository = "https://gitlab.freedesktop.org/neithanmo/csound_rs"
description = """
Raw bindings to libcsound64
High level Rust bindings are available in the `csound` crate
"""
[lib]
crate-type = ["rlib"]

[dependencies]
csound-sys = {path = "csound-sys", version = "0.1.0"}
libc = "0.2"
bitflags = "1.0.4"

#[badges]
#travis-ci = { repository = "dtolnay/quote" }
